### PR TITLE
Update netlink

### PR DESCRIPTION
**Pull request by adrianchiris**
update netlink version and remove out of tree modifications maintained in this repo.

### CODE REVIEW

**Comment by adrianchiris** [comment]
@moshe010 PTAL

**Comment by adrianchiris** [comment]
@moshe010 we could remove all things related to devlinkResource from mlxdevm-go now.
mlxdevm (gen)nl family does not support devlink resource only devlink family does. however that means we break API.

**Comment by moshe010** [comment]
should we document on which kernel or OFED it should work? I remember it was required upstream fix...

**Comment by adrianchiris** [comment]
> should we document on which kernel or OFED it should work? I remember it was required upstream fix...

the upstream fix was eventually to the documentation :) saying that for some commands we may have empty msg.

see[1] so the fix was eventually in netlink lib[2] (the WA we are removing here essentially)

[1] https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=8ad55b1e73c4e77656e2bea68fa2b484f33a6425
[2] https://github.com/vishvananda/netlink/pull/935

**Review by moshe010 — APPROVED** [review]

**Pull request merged**
